### ISSUE TITLE
Powiązanie aplikacji z bazą danych

### ISSUE THREAD

**Issue by kapi001** [kapi001/mosos_team#6]
Tutaj proszę zgłaszać wszelkie informacje związane z połączeniem aplikacji i bazy danych

**Comment by kapi001** [comment]
Wstępnie powiązano placeholder (tymczasowy odpowiednik) aplikacji z bazą danych. Dane są pobierane przez aplikacje i nie ma konfliktu między obiema częściami. Wykorzystano interfejs JDBC.

**Comment by mosos** [comment]
Do podkatalogu _database_ został dodany plik z pierwszymi wpisami **SQL** do naszej bazy danych.

**Comment by kapi001** [comment]
Wątek przeniesiono do issue o nazwie kodowanie #11 ze względu na powiązanie obu części. Zamykam
